apiVersion: v1
kind: ConfigMap
metadata:
  name: quilkin-config-simple-v2
data:
  quilkin.yaml: |  # quilkin configuration
    version: v1alpha1
    proxy:
      id: proxy-demo-simple-v2
      port: 26003
    static:
      filters:
        - name: quilkin.extensions.filters.debug.v1alpha1.Debug # Debug filter: every packet will be logged
          config:
            id: debug-1
        - name: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes # Capture and remove the authentication token
          config:
              strategy: PREFIX
              size: 3
              remove: true
              metadataKey: quilkin.dev
        - name: quilkin.extensions.filters.token_router.v1alpha1.TokenRouter
          config:
              metadataKey: quilkin.dev
      endpoints:
        - address: 127.0.0.1:7654
          metadata: # Metadata associated with the endpoint
            quilkin.dev:
              tokens:
                - YWJj # abc
                - MXg3aWp5Ng== # the connection byte array to route to, encoded as base64 (string value: 1x7ijy6)
                - OGdqM3YyaQ== # (string value: 8gj3v2i)
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server-v2
  labels:
    label: green
spec:
  replicas: 2
  strategy:
    # The replacement strategy for when the GameServer template is changed. Default option is "RollingUpdate",
    # "RollingUpdate" will increment by maxSurge value on each iteration, while decrementing by maxUnavailable on each
    # iteration, until all GameServers have been switched from one version to another.
    # "Recreate" terminates all non-allocated GameServers, and starts up a new set with the new details to replace them.
    type: RollingUpdate
    # Only relevant when `type: RollingUpdate`
    rollingUpdate:
      # the amount to increment the new GameServers by. Defaults to 25%
      maxSurge: 25%
      # the amount to decrements GameServers by. Defaults to 25%
      maxUnavailable: 25%
  template:
    spec:
      container: simple-game-server-v2
      ports:
      - name: default
        containerPort: 26003
        container: quilkin-simple-v2
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9091"
        spec:
          containers:
          - name: simple-game-server-v2
            image: gcr.io/cn-gaming-cicd/agones-simple-game-server:version2
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
          - name: quilkin-simple-v2
            image: us-docker.pkg.dev/quilkin/release/quilkin:0.1.0
            volumeMounts:
              - name: config-s-v2
                mountPath: "/etc/quilkin"
            livenessProbe:
              httpGet:
                path: /live
                port: 9091
              initialDelaySeconds: 3
              periodSeconds: 2
          volumes:
            - name: config-s-v2
              configMap:
                name: quilkin-config-simple-v2
