# Webhook URL 
# curl -X POST -H "application/json" "https://cloudbuild.googleapis.com/v1/projects/cn-gaming-cicd/triggers/fleet-config-trigger:webhook?key=AIzaSyBe45IJgmgE3Ssoekh77cl3Z1riBmG7N_I&secret=xh8twKFPVoA4SG2J9MxXY20sxD50EMVd" -d '{"cluster_name":"cluster-tf-1", "region":"us-central1", "config_file":"fleet_configs_simple.yaml"}'
steps:
  # step 1: ssh authentication
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - >

        echo "$$SSHKEY" > /root/.ssh/id_rsa

        chmod 400 /root/.ssh/id_rsa

        ssh-keyscan -t rsa gitlab.endpoints.cn-gaming-cicd.cloud.goog >>
        /root/.ssh/known_hosts

        ssh -T git@gitlab.endpoints.cn-gaming-cicd.cloud.goog
    entrypoint: bash
    secretEnv:
      - SSHKEY
    volumes:
      - name: ssh
        path: /root/.ssh
  # step 2: git clone terraform config file
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'git@gitlab.endpoints.cn-gaming-cicd.cloud.goog:gaming-ci-cd-automation/core.git'
      - ./core
    volumes:
      - name: ssh
        path: /root/.ssh
  # step 3: connect the cluster, apply the fleet config
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION --project $PROJECT_ID

          kubectl apply -f $_CONFIG_FILE
          
    dir: core/modules/agones
    volumes:
      - name: ssh
        path: /root/.ssh 
timeout: 3600s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ssh-key/versions/1
      env: SSHKEY
