apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 2
  template:
    spec:
      container: simple-game-server
      ports:
      - name: default
        containerPort: 7654
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9091"
        spec:
          containers:
          - name: simple-game-server
            imagePullPolicy: Always
            image: my-app-image
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
